version: "3"

services:

  client:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./packages/ui/public:/usr/share/nginx/html

  minio:
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    volumes:
      - "./data:/data"
    image: quay.io/minio/minio
    command: server /data

  couchdb:
    volumes:
      - ./data/couchdb:/opt/couchdb/data
    environment:
      - COUCHDB_USER=ROOTUSER
      - COUCHDB_PASSWORD=CHANGEME123
    ports:
      - "5984:5984"
    image: couchdb

  code:
    image: node
    volumes:
      - "./:/app"
    environment:
      - MINIO_URL=minio:9000
      - MINIO_ACCESS_KEY=ROOTUSER
      - MINIO_SECRET_KEY=CHANGEME123
      - MINIO_REPO_BUCKET=repos
      - REPO_STORAGE_DIRECTORY=/app/data/repos
    command:
      [
        "sh",
        "-c",
        "cd /app && yarn workspace @startcoding/code run start"
      ]
