version: "3"

services:

  client:
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./packages/frontend/ui/public:/usr/share/nginx/html
      - ./services/web/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certificates:/certificates
      - ./data/logs:/var/log
      
  minio:
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ACCESS_KEY=ROOTUSER
      - MINIO_SECRET_KEY=CHANGEME123
    volumes:
      - "./data/minio:/data"
    image: quay.io/minio/minio
    command: server /data

  couchdb:
    volumes:
      - ./data/couchdb:/opt/couchdb/data
    environment:
      - COUCHDB_USER=ROOTUSER
      - COUCHDB_PASSWORD=CHANGEME123
    ports:
      - "5984:5984"
    image: couchdb

  redis:
    ports:
      - 6379:6479
      - 8443:8443
    image: redis

  code:
    image: node
    ports:
      - 8081:8081
    volumes:
      - "./:/app"
    environment:
      - MINIO_URL=minio
      - MINIO_ACCESS_KEY=ROOTUSER
      - MINIO_SECRET_KEY=CHANGEME123
      - MINIO_REPO_BUCKET=repos
      - REPO_STORAGE_DIRECTORY=/app/data/repos
    command:
      [
        "sh",
        "-c",
        "cd /app && yarn workspace @startcoding/code run start"
      ]