name: Deploy to Live Channel

on:
  push:
    branches:
      - main
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - name: build
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: yarn
      - run: yarn workspaces run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: woofjs2-590cd
          channelId: live
      - uses: jsryudev/deploy-firebase-functions@v18.0.0
        env:
          FIREBASE_TOKEN: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          FIREBASE_PROJECT: woofjs2-590cd
